config/routes.rb
MavenTeaser::Application.routes.draw do

  devise_for :admins

  devise_for :advisors

  devise_for :users

  authenticated :user do
    root :to => "pages#home"
  end

  authenticated :advisor do
    root :to => "pages#home"
  end

  resources :matches

  resources :search_suggestions

  resources :emails

  resources :messages

  resources :conversations

  resources :questions do
    member { post :vote }
    resources :answers do
      member { post :vote }
    end
  end

  resources :advisors do
    resources :ratings
  end

  resources :users do
    resources :ratings
  end

  root :to => "pages#home"

  get "pages/rate_my_advisor"

  get "pages/find_an_advisor"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :answer, :score

  belongs_to :advisor

  belongs_to :question

  has_reputation :votes, source: :user, aggregated_by: :sum
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  before_filter :get_question

  def get_question
    @question = Question.find(params[:question_id])
  end

  def index
    @answers = @question.answers.find_with_reputation(:votes, :all, order: "votes desc")
  end

  def vote
    value = params[:type] == "up" ? 1 : -1
    @answer = @question.answers.find(params[:id])
    @answer.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back, notice: "Thank you for voting"
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = @question.answers.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = @question.answers.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = @question.answers.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = @question.answers.new(params[:answer])
    @answer.advisor = current_advisor


    respond_to do |format|
      if @answer.save
        format.html { redirect_to [@question, @answer], notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = @question.answers.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to [@question, @answer], notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = @question.answers.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to question_answers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div class="well well-small">
  Answered by <%= link_to answer.advisor.name, answer.advisor %>
  <table class="table">
    <tr>
      <td><%= answer.answer %></td>
    </tr>
    <tr>
      | <%= pluralize answer.reputation_for(:votes).to_i, "vote" %>
      <% if current_user && !current_user.voted_for?(answer) %>
      | <%= link_to "up", vote_question_answer_path(@question, answer, type: "up"), method: "post" %>
      | <%= link_to "down", vote_question_answer_path(@question,answer, type: "down"), method: "post" %>
      <% end %>
    </tr>
  </table>
</div>

app/views/answers/_form.html.erb
<%= simple_form_for([@question, @answer]) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :answer %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', question_answer_path(@question, @answer) %> |
<%= link_to 'Back', question_answers_path(@question) %>

app/views/answers/index.html.erb
<div class="well well-small">
    <%= link_to @question.title, @question %> Asked by <%= @question.user.name %>
      <table class="table">
      <tr>
        <td><%= @question.details %></td>
      </tr>
      <tr>
        <td>
          <%= pluralize @question.reputation_for(:votes).to_i, "vote" %>
          <% if current_user && !Question.evaluated_by(:votes, current_user).include?(@question) %>
          | <%= link_to "up", vote_question_path(@question, type: "up"), method: "post" %>
          | <%= link_to "down", vote_question_path(@question, type: "down"), method: "post" %>
        </td>
      </tr>
      <% end %>
    </table>
  <% @question.answers.each do |answer| %>
 <div class="well well-small">
  Answered by <%= link_to answer.advisor.name, answer.advisor %>
  <table class="table">
    <tr>
      <td><%= answer.answer %></td>
    </tr>
    <tr>
      | <%= pluralize answer.reputation_for(:votes).to_i, "vote" %>
      <% if current_user && !Answer.evaluated_by(:votes, current_user).include?(answer) %>
      | <%= link_to "up", vote_question_answer_path(question, answer, type: "up"), method: "post" %>
      | <%= link_to "down", vote_question_answer_path(question,answer, type: "down"), method: "post" %>
      <% end %>
    </tr>
  </table>
</div>
  <% end %>
</div>

app/views/answers/new.html.erb
<table>
	<tr>
		<td><strong><%= @question.title %></strong></td>
	</tr>
	<tr>
		<td><%= @question.details %></td>
	</tr>
</table>

<%= render 'form' %>

<%= link_to 'Back', question_answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="well well-small">
  Answered by <%= link_to @answer.advisor.name, @answer.advisor %>
  <table class="table">
    <tr>
      <td><%= @answer.answer %></td>
    </tr>
    <tr>
      | <%= pluralize @answer.reputation_for(:votes).to_i, "vote" %>
      <% if current_user && !Answer.evaluated_by(:votes, current_user).include?(@answer) %>
      | <%= link_to "up", vote_question_answer_path(@question, @answer, type: "up"), method: "post" %>
      | <%= link_to "down", vote_question_answer_path(@answer, type: "down"), method: "post" %>
      <% end %>
    </tr>
  </table>
</div>

<% if current_user && Answer.evaluated_by(:votes, current_user).include?(@answer) %>
  <%= link_to 'Edit', edit_question_answer_path(@question, @answer) %> |
<% end %>
<%= link_to 'Back', question_answers_path(@question) %>