config/routes.rb
MavenTeaser::Application.routes.draw do

  devise_for :admins

  devise_for :advisors

  devise_for :users

  authenticated :user do
    root :to => "pages#home"
  end

  authenticated :advisor do
    root :to => "pages#home"
  end

  resources :matches

  resources :search_suggestions

  resources :emails

  resources :messages

  resources :conversations

  resources :questions do
    member { post :vote }
    resources :answers do
      member { post :vote }
    end
  end

  resources :advisors do
    resources :ratings
  end

  resources :users do
    resources :ratings
  end

  root :to => "pages#home"

  get "pages/rate_my_advisor"

  get "pages/find_an_advisor"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :active_passive, :follower_contrarian, :high_iq_low_iq, :high_touch_low_touch

  belongs_to :users
  belongs_to :advisors

  def calculate_match(user, advisor)
  	self.active_passive_score = 1- (@user.active_passive - @advisor.active_passive).abs
  	self.high_touch_low_touch = 1- (@user.high_touch_low_touch - @advisor.high_touch_low_touch).abs
  	self.follower_contrarian = 1- (@user.follower_contrarian - @advisor.follower_contrarian).abs
  	self.final_match = (self.active_passive + self.high_touch_low_touch + self.follower_contrarian) / 3
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matches }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = Match.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/new
  # GET /matches/new.json
  def new
    @match = Match.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
  end

  # POST /matches
  # POST /matches.json
  def create
    @user = current_user
    @match = Match.new(params[:match])

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render json: @match, status: :created, location: @match }
      else
        format.html { render action: "new" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /matches/1
  # PUT /matches/1.json
  def update
    @match = Match.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= simple_form_for(@match) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :active_passive %>
    <%= f.input :high_touch_low_touch %>
    <%= f.input :follower_contrarian %>
    <%= f.input :high_iq_low_iq %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h1>Listing matches</h1>

<table>
  <tr>
    <th>Active passive</th>
    <th>High touch low touch</th>
    <th>Follower contrarian</th>
    <th>High iq low iq</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @matches.each do |match| %>
  <tr>
    <td><%= match.active_passive %></td>
    <td><%= match.high_touch_low_touch %></td>
    <td><%= match.follower_contrarian %></td>
    <td><%= match.high_iq_low_iq %></td>
    <td><%= link_to 'Show', match %></td>
    <td><%= link_to 'Edit', edit_match_path(match) %></td>
    <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Active passive:</b>
  <%= @match.active_passive %>
</p>

<p>
  <b>High touch low touch:</b>
  <%= @match.high_touch_low_touch %>
</p>

<p>
  <b>Follower contrarian:</b>
  <%= @match.follower_contrarian %>
</p>

<p>
  <b>High iq low iq:</b>
  <%= @match.high_iq_low_iq %>
</p>


<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>