config/routes.rb
MavenTeaser::Application.routes.draw do

  devise_for :admins

  devise_for :advisors

  devise_for :users

  authenticated :user do
    root :to => "pages#home"
  end

  authenticated :advisor do
    root :to => "pages#home"
  end

  resources :matches

  resources :search_suggestions

  resources :emails

  resources :messages

  resources :conversations

  resources :questions do
    member { post :vote }
    resources :answers do
      member { post :vote }
    end
  end

  resources :advisors do
    resources :ratings
  end

  resources :users do
    resources :ratings
  end

  root :to => "pages#home"

  get "pages/rate_my_advisor"

  get "pages/find_an_advisor"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/advisor.rb
class Advisor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  acts_as_messageable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :address, :email, :finra_disclosures, :finra_status, :firm, :name, :phone, :sec_disclosures, :sec_status, :advisor_type, :website
  attr_accessible :avatar

  has_attached_file :avatar, 
                    :styles => { 
                      :medium => "200x200>", 
                      :thumb => "100x100>" }, 
                    :default_url => "/images/:style/missing.png"

  has_many :ratings

  has_many :answers

  has_many :questions, :through => :answers

  has_many :matches
  has_many :users, :through => :matches

  has_reputation :answering_skill,
      :source => { :reputation => :votes, :of => :answers }

  def update_composite_rating
    self.composite_rating = self.ratings.average('trust') * 0.8 + self.ratings.average('communication') * 0.1 + self.ratings.average('expertise') * 0.1
    self.save
  end

  def update_active_passive
    self.active_passive = self.ratings.average('active')
    self.save
  end

  def update_high_touch_low_touch
    self.high_touch_low_touch = self.ratings.average('high_touch')
    self.save
  end

  def update_follower_contrarian
    self.follower_contrarian = self.ratings.average('follower')
    self.save
  end

  def update_high_iq_low_iq
    self.high_iq_low_iq = self.ratings.average('high_iq')
    self.save
  end

  def self.search(search)
	  if search
	    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
	  else
	    find(:all)
	  end
	end

  #Returning the email address of the model if an email should be sent for this object (Message or Notification).
  #If no mail has to be sent, return nil.
  def mailboxer_email(advisor)
    #Check if an email should be sent for that object
    #if true
    return "define_email@on_your.model"
    #if false
    #return nil
  end

end

app/controllers/advisors_controller.rb
class AdvisorsController < ApplicationController
  # GET /advisors
  # GET /advisors.json

  def index
    @advisors = Advisor.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @advisors }
    end
  end

  # GET /advisors/1
  # GET /advisors/1.json
  def show
    @advisor = Advisor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @advisor }
    end
  end

  # GET /advisors/new
  # GET /advisors/new.json
  def new
    @advisor = Advisor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @advisor }
    end
  end

  # GET /advisors/1/edit
  def edit
    @advisor = Advisor.find(params[:id])
  end

  # POST /advisors
  # POST /advisors.json
  def create
    @advisor = Advisor.new(params[:advisor])

    respond_to do |format|
      if @advisor.save
        format.html { redirect_to @advisor, notice: 'Advisor was successfully created.' }
        format.json { render json: @advisor, status: :created, location: @advisor }
      else
        format.html { render action: "new" }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /advisors/1
  # PUT /advisors/1.json
  def update
    @advisor = Advisor.find(params[:id])

    respond_to do |format|
      if @advisor.update_attributes(params[:advisor])
        format.html { redirect_to @advisor, notice: 'Advisor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advisors/1
  # DELETE /advisors/1.json
  def destroy
    @advisor = Advisor.find(params[:id])
    @advisor.destroy

    respond_to do |format|
      format.html { redirect_to advisors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
end

app/views/advisors/_contact_form.html.erb
<%= simple_form_for :message, :url => url_for(:action => 'create', :controller => 'messages')  do |f| %>
	<%= f.input :body %>
	<%= f.input :subject %>
	<%= f.submit %>
<% end %>

app/views/advisors/_form.html.erb
<%= form_for(@advisor) do |f| %>
  <% if @advisor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advisor.errors.count, "error") %> prohibited this advisor from being saved:</h2>

      <ul>
      <% @advisor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :firm %><br />
    <%= f.text_field :firm %>
  </div>
  <div class="field">
    <%= f.label :advisor_type %><br />
    <%= f.text_field :advisor_type %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :sec_status %><br />
    <%= f.text_field :sec_status %>
  </div>
  <div class="field">
    <%= f.label :sec_disclosures %><br />
    <%= f.number_field :sec_disclosures %>
  </div>
  <div class="field">
    <%= f.label :finra_status %><br />
    <%= f.text_field :finra_status %>
  </div>
  <div class="field">
    <%= f.label :finra_disclosures %><br />
    <%= f.number_field :finra_disclosures %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/advisors/edit.html.erb
<h1>Edit profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @advisor %> |
<%= link_to 'Back', advisors_path %>

app/views/advisors/index.html.erb
<table>
<% @advisors.each do |advisor| %>
  <tr>
    <td>
    		<%= image_tag advisor.avatar.url(:thumb) %>
        <%= link_to advisor.name, advisor %>
    </td>
  </tr>
<% end %>
</table>

<br />

app/views/advisors/new.html.erb
<h1>New advisor</h1>

<%= render 'form' %>

<%= link_to 'Back', advisors_path %>

app/views/advisors/show.html.erb
<p>
  <h3>
    <%= @advisor.name %>
       | <%= link_to "Edit profile", edit_advisor_path %>
  </h3>
</p>

<p>
  <% unless !@advisor.avatar? %>
  <%= image_tag @advisor.avatar.url(:medium) %>
  <% end %>
</p>

<%= render 'contact_form' %>

<% unless current_advisor %>
  <p>
    <%= link_to "Rate this advisor!", new_advisor_rating_path(@advisor), class: "btn btn-small btn-success" %>
  </p>
  <% end %>

<% if @advisor.ratings.blank? %>
<p>
  This advisor has not yet been rated.
</p>
<% else %>
<p>
  Trust: 
      <%= @advisor.ratings.average('trust').round(1) %>
</p>
<p>
  Communication: <%= @advisor.ratings.average('communication').round(1) %>
</p>
<p>
  Expertise: <%= @advisor.ratings.average('expertise').round(1) %>
</p>
<% end %>

<p>
Financial Expertise Votes: <span class="badge badge-success"><%= @advisor.reputation_for(:answering_skill).to_i %></span>
</p>

<p>
  <strong>Questions answered:</strong>
</p>
  <% if @advisor.answers.empty? %>
    <p>
      <%= link_to "Advisor has not answered any questions", questions_path %>
    </p>
  <% end %>

  <% @advisor.answers.each do |answer| %>
    <p>
    <%= link_to answer.question.title, answer.question %><span class="label"><%= answer.question.topic %></span>
    </p>
  <% end %>

<p>
  <b>Firm:</b>
  <%= @advisor.firm %>
</p>

<p>
  <b>Advisor type:</b>
  <%= @advisor.advisor_type %>
</p>

<p>
  <b>Address:</b>
  <%= @advisor.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @advisor.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @advisor.email %>
</p>

<p>
  <b>Website:</b>
  <%= @advisor.website %>
</p>

<p>
  <b>Sec status:</b>
  <%= @advisor.sec_status %>
</p>

<p>
  <b>Sec disclosures:</b>
  <%= @advisor.sec_disclosures %>
</p>

<p>
  <b>Finra status:</b>
  <%= @advisor.finra_status %>
</p>

<p>
  <b>Finra disclosures:</b>
  <%= @advisor.finra_disclosures %>
</p>