config/routes.rb
MavenTeaser::Application.routes.draw do

  devise_for :admins

  devise_for :advisors

  devise_for :users

  authenticated :user do
    root :to => "pages#home"
  end

  authenticated :advisor do
    root :to => "pages#home"
  end

  resources :matches

  resources :search_suggestions

  resources :emails

  resources :messages

  resources :conversations

  resources :questions do
    member { post :vote }
    resources :answers do
      member { post :vote }
    end
  end

  resources :advisors do
    resources :ratings
  end

  resources :users do
    resources :ratings
  end

  root :to => "pages#home"

  get "pages/rate_my_advisor"

  get "pages/find_an_advisor"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/advisor.rb
class Advisor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  acts_as_messageable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :address, :email, :finra_disclosures, :finra_status, :firm, :name, :phone, :sec_disclosures, :sec_status, :advisor_type, :website
  attr_accessible :avatar

  has_attached_file :avatar, 
                    :styles => { 
                      :medium => "200x200>", 
                      :thumb => "100x100>" }, 
                    :default_url => "/images/:style/missing.png"

  has_many :ratings

  has_many :answers

  has_many :questions, :through => :answers

  has_many :matches
  has_many :users, :through => :matches

  has_reputation :answering_skill,
      :source => { :reputation => :votes, :of => :answers }

  def update_composite_rating
    self.composite_rating = self.ratings.average('trust') * 0.8 + self.ratings.average('communication') * 0.1 + self.ratings.average('expertise') * 0.1
    self.save
  end

  def update_active_passive
    self.active_passive = self.ratings.average('active')
    self.save
  end

  def update_high_touch_low_touch
    self.high_touch_low_touch = self.ratings.average('high_touch')
    self.save
  end

  def update_follower_contrarian
    self.follower_contrarian = self.ratings.average('follower')
    self.save
  end

  def update_high_iq_low_iq
    self.high_iq_low_iq = self.ratings.average('high_iq')
    self.save
  end

  def self.search(search)
	  if search
	    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
	  else
	    find(:all)
	  end
	end

  #Returning the email address of the model if an email should be sent for this object (Message or Notification).
  #If no mail has to be sent, return nil.
  def mailboxer_email(advisor)
    #Check if an email should be sent for that object
    #if true
    return "define_email@on_your.model"
    #if false
    #return nil
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :answer, :score

  belongs_to :advisor

  belongs_to :question

  has_reputation :votes, source: :user, aggregated_by: :sum
end

app/models/email.rb
class Email < ActiveRecord::Base
  attr_accessible :email

  validates_presence_of :email

  validates_uniqueness_of :email
end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :active_passive, :follower_contrarian, :high_iq_low_iq, :high_touch_low_touch

  belongs_to :users
  belongs_to :advisors

  def calculate_match(user, advisor)
  	self.active_passive_score = 1- (@user.active_passive - @advisor.active_passive).abs
  	self.high_touch_low_touch = 1- (@user.high_touch_low_touch - @advisor.high_touch_low_touch).abs
  	self.follower_contrarian = 1- (@user.follower_contrarian - @advisor.follower_contrarian).abs
  	self.final_match = (self.active_passive + self.high_touch_low_touch + self.follower_contrarian) / 3
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :details, :title, :topic

  belongs_to :user

  has_many :answers

  has_reputation :votes, :source => :user, :aggregated_by => :sum
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :communication, :expertise, :trust, :advisor, :active, :high_touch, :follower, :high_iq

  validates_presence_of :trust, :communication, :expertise, :on => :create, :message => "can't be blank"

  belongs_to :advisor
  belongs_to :user

  after_commit :update_advisor_composite_rating
  after_commit :update_advisor_active_passive
  after_commit :update_advisor_high_touch_low_touch
  after_commit :update_advisor_follower_contrarian
  after_commit :update_advisor_high_iq_low_iq

  def update_advisor_composite_rating
    advisor.update_composite_rating
  end

	def update_advisor_active_passive
    advisor.update_active_passive
  end

  def update_advisor_high_touch_low_touch
    advisor.update_high_touch_low_touch
  end

  def update_advisor_follower_contrarian
    advisor.update_follower_contrarian
  end

  def update_advisor_high_iq_low_iq
    advisor.update_high_iq_low_iq
  end  

end

app/models/search_suggestion.rb
class SearchSuggestion < ActiveRecord::Base
  attr_accessible :popularity, :term
  
  def self.terms_for(prefix)
    Rails.cache.fetch(["search-terms", prefix]) do
      suggestions = where("term like ?", "#{prefix}_%")
      suggestions.order("popularity desc").limit(10).pluck(:term)
    end
  end
  
  def self.index_advisors
    Advisor.find_each do |advisor|
      index_term(advisor.name)
      advisor.name.split.each { |t| index_term(t) }
    end
  end
  
  def self.index_term(term)
    where(term: term.downcase).first_or_initialize.tap do |suggestion|
      suggestion.increment! :popularity
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  acts_as_messageable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  #after_commit :update_matches

  #acts_as_messageable

  has_many :ratings

  has_many :questions

  has_many :matches
  has_many :advisors, :through => :matches

  def update_matches(advisor)
    advisor.each do |advisor|
      calculate_match(self, advisor)
    end
  end

  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"]
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	autocomplete :advisor, :name

	def home
		@questions = Question.all
	end

end

app/helpers/advisors_helper.rb
module AdvisorsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_background.html.erb
<body background="https://s3.amazonaws.com/maven_teaser/maven_teaser_background_optimized.jpg">

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">

        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <!-- Be sure to leave the brand out there if you want it shown -->
        <a class="brand", href="/" ><i class="icon-leaf"></i>MavenMarket</a>

        <!-- Everything you want hidden at 940px or less, place within here -->
        <div class="nav-collapse collapse">
          <ul class="nav pull-left">
              <li><%= link_to "Find An Advisor", "/pages/find_an_advisor" %></li>
              <li><%= link_to "Rate My Advisor", "/pages/rate_my_advisor" %></li>
              <li><%= link_to "Ask A Financial Question", questions_path %></li>
            <% if advisor_signed_in? %>
              <li><%= link_to "My Profile", current_advisor %></li>
              <li><%= link_to "Financial Questions", questions_path %></li>
            <% end %>
          </ul>
          <ul class="nav pull-right">
            <% if user_signed_in? %>
              <li><%= link_to "Signed in as #{current_user.name}", current_user %></li>
              <li><a href="messages">Inbox <span class="badge badge-success"><% unless current_user.mailbox.inbox.empty? %><%= current_user.mailbox.inbox.count %><% end %></span></a></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :id => "logout_button" %></li>
            <% elsif advisor_signed_in? %>
              <li><%= link_to "Signed in as #{current_advisor.name}", current_advisor %></li>
              <li><%= link_to "Logout", destroy_advisor_session_path, method: :delete, :id => "logout_button" %></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path, :id => "login_button" %></li>
              <li><%= link_to "Advisor Login", new_advisor_session_path, :id => "login_button" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>MavenMarket</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <!-- <link href="/assets/css/bootstrap-responsive.css" rel="stylesheet"> !-->
	</head>
	<body>

	<%= render "layouts/header" %>
	
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div,msg,class: "alert alert-#{name}") %>
		<% end %>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<table class="table">	
	<div>
	  <h2>Advisor Match</h2>
	  <p>We use data and behavioral science to match you with the world's best advisors</p>
	  <p>
	    <%= link_to "Get started", "/pages/find_an_advisor", class: "btn btn-large btn-success" %>
	  </p>
	<div>
	<tr>
		<td>
			<div>	
				<h3>Find Advisor By Name</h3>
					<%= form_tag advisors_path, :class => "form-inline", method: :get do %>
				  <%= text_field_tag :search, nil, :placeholder => "Enter advisor name" %>
				  <%= submit_tag "Search", :class => "btn", name:nil %>
			<% end %>
			</div>
		</td>
	</tr>
	<tr>
		<td>
			<h3>
				Financial Questions Answered By Experts
			</h3>
		</td>
	</tr>
	<tr>
		<td>
			<%= form_tag questions_path, :class => "form-inline", method: :get do %>
		  <%= text_field_tag :search, nil, :placeholder => "Search for a topic" %>
		  <%= submit_tag "Search", :class => "btn", name:nil %>
		  <% end %>
			<%= link_to "Ask a new question", "/questions", class: "btn btn-success" %>
		</td>
	</tr>
	<tr>
		<td>		
			<%= render @questions.sort_by(&:updated_at).reverse %>
		</td>
	</tr>
		
</table>

app/views/pages/rate_my_advisor.html.erb
<body>
<h3>
	First, find your advisor by name:
</h3>
		<%= form_tag advisors_path, :class => "form-inline", method: :get do %>
	  <%= text_field_tag :search %>
	  <%= submit_tag "Search", :class => "btn", name:nil %>
<% end %>

<!-- 	<h3>Overall Ratings</h3>

	<table class="rating">
		<tr>
			<td>
				<h4>Trust</h4>
			</td>
			<td class="rating">
				<input type="radio" id="star5" name="rating" value="5" /><label for="star5" title="Rocks!">5 stars</label>
				<input type="radio" id="star4" name="rating" value="4" /><label for="star4" title="Pretty good">4 stars</label>
				<input type="radio" id="star3" name="rating" value="3" /><label for="star3" title="Okay">3 stars</label>
				<input type="radio" id="star2" name="rating" value="2" /><label for="star2" title="Pretty bad">2 stars</label>
				<input type="radio" id="star1" name="rating" value="1" /><label for="star1" title="Very bad">1 star</label>
			</td>
		</tr>
		<tr>
			<td>
				<h4>Communication</h4>
			</td>
			<td class="rating1">
				<input type="radio" id="star51" name="rating1" value="5" /><label for="star51" title="Rocks!">5 stars</label>
				<input type="radio" id="star41" name="rating1" value="4" /><label for="star41" title="Pretty good">4 stars</label>
				<input type="radio" id="star31" name="rating1" value="3" /><label for="star31" title="Okay">3 stars</label>
				<input type="radio" id="star21" name="rating1" value="2" /><label for="star21" title="Pretty bad">2 stars</label>
				<input type="radio" id="star11" name="rating1" value="1" /><label for="star11" title="Very bad">1 star</label>
			</td>
		</tr>
		<tr>
			<td>
				<h4>Expertise</h4>
			</td>
			<td class="rating2">
				<input type="radio" id="star52" name="rating2" value="5" /><label for="star52" title="Rocks!">5 stars</label>
				<input type="radio" id="star42" name="rating2" value="4" /><label for="star42" title="Pretty good">4 stars</label>
				<input type="radio" id="star32" name="rating2" value="3" /><label for="star32" title="Okay">3 stars</label>
				<input type="radio" id="star22" name="rating2" value="2" /><label for="star22" title="Pretty bad">2 stars</label>
				<input type="radio" id="star12" name="rating2" value="1" /><label for="star12" title="Very bad">1 star</label>
			</td>
		</tr>
	</table> -->